name: Documentation

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-arch: [x64]
        julia-version: ['1.3.0']
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name:  Setup virtual display
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install xorg-dev xvfb
          sudo Xvfb :99 -screen 0 1024x768x24 &
        shell: bash
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Add registry
        run: |
          julia --color=yes --project -e 'using Pkg; Registry.add(RegistrySpec(url = "https://github.com/Lyceum/LyceumRegistry.git"))'
          julia --color=yes --project -e 'using Pkg; Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"))'
        shell: bash
      - uses: julia-actions/julia-buildpkg@master
      - name: Build and deploy
        env:
          MUJOCO_KEY: ${{ secrets.MUJOCO_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DISPLAY: ':99'
        run: julia --project -e 'using LyceumDocs; LyceumDocs.make()'
